export const items = [

    {
   
 
   "GoodSold": { textDragging:false,
       isDragging:true,name: "GoodSold", coins: 24,p:"Goods-sold" ,divClass:"Goods-sold",circle:"circle"},
   "RMP": { textDragging:false,isDragging:true, name: "RMP", coins: 15 ,p:"",span:"RMP",circle:"circle",divClass:"Rmp"},
   "dividends": { textDragging:false,isDragging:true,
        name: "dividends", 
        coins: 7,
        span:"dividends",
        smallCircle:"owners-circle",
        circle:"circle"},
   "equity": { textDragging:false,isDragging:true,
           name: "equity", 
           coins: 15,
           span:"equity",
           smallCircle:"circle",
           circle:"circle"},
   "interest": { textDragging:false,isDragging:true,
           name: "interest", 
           coins: 6,
           span:"interest",
           smallCircle:"",
           circle:"circle"},
   "liabilities": { textDragging:false,isDragging:true,
           name: "liabilities", 
           coins: 6,
           span:"liabilities",
           smallCircle:"circle ",
           circle:"circle"},
   "taxes": { textDragging:false,isDragging:true,
           name: "taxes", 
           coins: 60,
           span:"taxes",
           smallCircle:"circle ",
           circle:"circle"},
   "Cash": { textDragging:false,isDragging:true,
           name: "Cash", 
           coins: 14,
           span:"Cash",
           smallCircle:"circle ",
           circle:"circle"},
   "accountsReceivable": { textDragging:false,isDragging:true,
           name: "accountsReceivable", 
           coins: 14,
           span:"accounts receivable",
           smallCircle:"cash-circle ",
           circle:"circle"},
   "stockOfMaterial": { textDragging:false,isDragging:true,
               name: "stockOfMaterial", 
               coins: 5,
               span:"Stock of Material",
               smallCircle:"circle ",
               circle:"circle"},
   "manufacturing": { textDragging:false,isDragging:true,
               name: "manufacturing", 
               coins: 6,
               span:"manufacturing",
               smallCircle:"circle ",
               circle:"circle"},
   

}
,    {
   
 
   "GoodSold": { textDragging:false,isDragging:true,name: "GoodSold", coins: 224,p:"Goods-sold" ,divClass:"Goods-sold",circle:"circle"},
   "RMP": { textDragging:false, name: "RMP", coins: 115 ,isDragging:true,p:"",span:"RMP",circle:"circle",divClass:"Rmp"},
   "dividends": { textDragging:false,isDragging:true,
        name: "dividends", 
        coins: 100,
        span:"dividends",
        smallCircle:"owners-circle",
        circle:"circle"},
   "equity": { textDragging:false,isDragging:true,
           name: "equity", 
           coins: 151,
           span:"equity",
           smallCircle:"circle",
           circle:"circle"},
   "interest": { textDragging:false,isDragging:true,
           name: "interest", 
           coins: 611,
           span:"interest",
           smallCircle:"",
           circle:"circle"},
   "liabilities": { textDragging:false,isDragging:true,
           name: "liabilities", 
           coins: 615,
           span:"liabilities",
           smallCircle:"circle ",
           circle:"circle"},
   "taxes": { textDragging:false,isDragging:true,
           name: "taxes", 
           coins: 600,
           span:"taxes",
           smallCircle:"circle ",
           circle:"circle"},
   "Cash": { textDragging:false,isDragging:true,
           name: "Cash", 
           coins: 140,
           span:"Cash",
           smallCircle:"circle ",
           circle:"circle"},
   "accountsReceivable": { textDragging:false,isDragging:true,
           name: "accountsReceivable", 
           coins: 104,
           span:"accounts receivable",
           smallCircle:"cash-circle ",
           circle:"circle"},
   "stockOfMaterial": { textDragging:false,isDragging:true,
               name: "stockOfMaterial", 
               coins: 555,
               span:"Stock Of Material",
               smallCircle:"circle ",
               circle:"circle"},
   "manufacturing": { textDragging:false,isDragging:true,
                   name: "manufacturing", 
                   coins: 66,
                   span:"manufacturing",
                   smallCircle:"circle ",
                   circle:"circle"},

}];
export const getData=(team)=>{
   return items[team-1]

}
 
